name: AWS SSM Paramter store retrieve
description: Action used to retrive AWS SSM Paramater store
author: João Lemos - jhflemos@gmail.com

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: play-circle
  color: green

inputs:
  ssm-path:
    description: SSM Paramater store path to be retrieve
    required: true
  withDecryption:
    description: SSM Paramater store description to be retrieve
    required: false
    default: 'false'
  parameterFilters:
    description: Filters to limit the request results
    required: false
    default: ''
  exportToEnv:
    description: Export SSM parameters as GitHub Actions environment
    required: false
    default: 'true'
  output:
    description: Output type to create the file with SSM parameters
    required: false
    default: ''
  fileName:
    description: Name for the output file
    required: false
    default: 'env'
  region:
    description: AWS region
    required: true
  debug:
    description: Active debug mode
    required: false
    default: 'false'

outputs:
  values:
    description: Your output description here

runs:
  using: node24
  main: dist/index.cjs
